version: '3.7'

services:
  api:
    image: inf22dw2g21/adonis-api
    ports:
      - '3333:3333'
    depends_on:
      - db

  db:
    image: inf22dw2g21/mysql-5.7
    ports:
      - '3306:3306'
    command: --innodb_use_native_aio=0
    environment:
      MYSQL_DATABASE: adonis
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
